version: '3'
services:
  exonum-node-1:
    image: stq-blockchain
    build:
      context: .
      dockerfile: Dockerfile.exonum
    container_name: stq-blockchain
    working_dir: /app
    command: ["sh", "-c", "cargo run"]
    volumes:
      - ..:/app
      - exonum_cargo_cache:/usr/local/cargo
    ports:
      - 8000:8000
    stdin_open: true


volumes:
  exonum_cargo_cache:
